format = """
$directory\
$character"""

right_format = """
$git_branch\
$git_status\
$nodejs\
$golang"""

add_newline = false

[character]
success_symbol = "[➜](fg:#A7C080) "
error_symbol = "[✘](fg:#E67E80) "

[directory]
truncation_length = 1
style = "fg:#7FBBB3"

[git_status]
format = '[$staged$modified$renamed$deleted$untracked$conflicted$ahead_behind]($style)'
style = ""

	staged     = '[+${count} ](fg:#A7C080)'
	modified   = '[!${count} ](fg:#DBBC7F)'
	renamed    = '[»${count} ](fg:#D699B6)'
	deleted    = '[-${count} ](fg:#E67E80)'
	untracked  = '[?${count} ](fg:#83C092)'
	stashed    = '[≡${count} ](fg:#DBBC7F)'
	conflicted = '[✖${count} ](fg:#E67E80)'

	ahead      = '[⇡${count} ](fg:#A7C080)'
	behind     = '[⇣${count} ](fg:#E69875)'
	diverged   = '[⇕⇡${ahead_count}⇣${behind_count} ](fg:#D699B6)'

[git_branch]
symbol = " "
style = "fg:#DBBC7F"

[nodejs]
disabled = false
format = '[ $symbol( $version) ]($style)'
symbol = "📦"
style = "fg:#DBBC7F"

[golang]
format = "[ $symbol( $version) ]($style)"
detect_files = ["go.mod", "go.sum", "glide.yaml", "go.sum"]
disabled = false
symbol = "🐹"
style = "fg:#83C092"

[python]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[php]
disabled = true

[java]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[terraform]
disabled = true

[docker_context]
disabled = true
